INSERT INTO instrumentation_main (DOCUMENT_NAME, DOCUMENT_DESCRIPTION,
DOCUMENT_FILE_NAME, DOCUMENT_TYPE, 
MANDATORY_UA, MANDATORY_RK, MANDATORY_RU,
APPLICATION_GENERAL, APPLICATION_MEASUREMENT, APPLICATION_INSTRUMENTATION,
APPLICATION_SAFETY, APPLICATION_ASUTP, APPLICATION_PROCESS,
APPLICATION_PIPING, APPLICATION_ELECTRICAL, APPLICATION_CONSTRUCTION,
APPLICATION_CABLE_ROUTING, APPLICATION_PID, APPLICATION_SPDS_ESKD, APPLICATION_DOCUMENTS_DESIGN,
NOTES) VALUES ('ТУ-газ-86', 'ТРЕБОВАНИЯ К УСТАНОВКЕ СИГНАЛИЗАТОРОВ И ГАЗОАНАЛИЗАТОРОВ',
'tu-gas-86.pdf', 'ТУ',
true, true, true,
false, false, true,
true, false, true,
false, false, false,
false, false, false, true,
'Нормативный документ по установке и расположению датчиков ДВК и ПДК');
INSERT INTO instrumentation_main (DOCUMENT_NAME, DOCUMENT_DESCRIPTION,
DOCUMENT_FILE_NAME, DOCUMENT_TYPE, 
MANDATORY_UA, MANDATORY_RK, MANDATORY_RU,
APPLICATION_GENERAL, APPLICATION_MEASUREMENT, APPLICATION_INSTRUMENTATION,
APPLICATION_SAFETY, APPLICATION_ASUTP, APPLICATION_PROCESS,
APPLICATION_PIPING, APPLICATION_ELECTRICAL, APPLICATION_CONSTRUCTION,
APPLICATION_CABLE_ROUTING, APPLICATION_PID, APPLICATION_SPDS_ESKD, APPLICATION_DOCUMENTS_DESIGN,
NOTES) VALUES ('СТ РК 2.108-2006', 'ГАЗОАНАЛИЗАТОРЫ АВТОМАТИЧЕСКИЕ НЕПРЕРЫВНОГО ДЕЙСТВИЯ. ОБЩИЕ ТРЕБОВАНИЯ К УСТАНОВКЕ, ТЕХНИЧЕСКОМУ ОБСЛУЖИВАНИЮ И МОНТАЖУ',
'st.rk-2-108-2006.pdf', 'СТ РК',
false, true, false,
false, false, true,
true, false, true,
false, false, false,
false, false, false, true,
'Общие требования к установке, техническому обслуживанию и поверке сигнализаторов предельно допустимых концентраций (сигнализаторов ПДК)');
INSERT INTO instrumentation_main (DOCUMENT_NAME, DOCUMENT_DESCRIPTION,
DOCUMENT_FILE_NAME, DOCUMENT_TYPE, 
MANDATORY_UA, MANDATORY_RK, MANDATORY_RU,
APPLICATION_GENERAL, APPLICATION_MEASUREMENT, APPLICATION_INSTRUMENTATION,
APPLICATION_SAFETY, APPLICATION_ASUTP, APPLICATION_PROCESS,
APPLICATION_PIPING, APPLICATION_ELECTRICAL, APPLICATION_CONSTRUCTION,
APPLICATION_CABLE_ROUTING, APPLICATION_PID, APPLICATION_SPDS_ESKD, APPLICATION_DOCUMENTS_DESIGN,
NOTES) VALUES ('СТ РК 2.109-2006', 'Сигнализаторы довзрывоопасных концентраций непрерывного действия. Общие требования к установке, техническому обслуживанию и поверке',
'st.rk-2-109-2006.pdf', 'СТ РК',
false, true, false,
false, false, true,
true, false, true,
false, false, false,
false, false, false, true,
'Общие требования к установке, техническому обслуживанию и поверке сигнализаторов довзрывоопасных концентраций (далее - сигнализаторы ДВК)');


